### ISSUE TITLE
[UX] Cannot cancel "Edit username" action

### ISSUE THREAD

**Issue by lunatic999** [mvitolo/unoxdue_ios#1]
**Type of issue**: UX

**Steps to reproduce**
- Open the app
- Go to the Profile tab
- Tap edit beside the username

**Expected result**
- A popup opens and I am able to both save my modifications and to cancel if I want to come back

**Actual result**
- I am forced to apply the modification (only "Save" button is present)

**Comment by mvitolo** [comment]
bug... working on it

**Comment by mvitolo** [comment]
Fixed available from 1.0.4
